// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/pubsub/v1/pubsub.proto

package pubsubv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PushPubsubMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PushPubsubMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushPubsubMessageRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PushPubsubMessageRequestMultiError, or nil if none found.
func (m *PushPubsubMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PushPubsubMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Subscription

	if m.GetMessage() == nil {
		err := PushPubsubMessageRequestValidationError{
			field:  "Message",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PushPubsubMessageRequestValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PushPubsubMessageRequestValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PushPubsubMessageRequestValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PushPubsubMessageRequestMultiError(errors)
	}

	return nil
}

// PushPubsubMessageRequestMultiError is an error wrapping multiple validation
// errors returned by PushPubsubMessageRequest.ValidateAll() if the designated
// constraints aren't met.
type PushPubsubMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushPubsubMessageRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushPubsubMessageRequestMultiError) AllErrors() []error { return m }

// PushPubsubMessageRequestValidationError is the validation error returned by
// PushPubsubMessageRequest.Validate if the designated constraints aren't met.
type PushPubsubMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushPubsubMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushPubsubMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushPubsubMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushPubsubMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushPubsubMessageRequestValidationError) ErrorName() string {
	return "PushPubsubMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PushPubsubMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushPubsubMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushPubsubMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushPubsubMessageRequestValidationError{}

// Validate checks the field values on PushPubsubMessageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PushPubsubMessageResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushPubsubMessageResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PushPubsubMessageResponseMultiError, or nil if none found.
func (m *PushPubsubMessageResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PushPubsubMessageResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PushPubsubMessageResponseMultiError(errors)
	}

	return nil
}

// PushPubsubMessageResponseMultiError is an error wrapping multiple validation
// errors returned by PushPubsubMessageResponse.ValidateAll() if the
// designated constraints aren't met.
type PushPubsubMessageResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushPubsubMessageResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushPubsubMessageResponseMultiError) AllErrors() []error { return m }

// PushPubsubMessageResponseValidationError is the validation error returned by
// PushPubsubMessageResponse.Validate if the designated constraints aren't met.
type PushPubsubMessageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushPubsubMessageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushPubsubMessageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushPubsubMessageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushPubsubMessageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushPubsubMessageResponseValidationError) ErrorName() string {
	return "PushPubsubMessageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PushPubsubMessageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushPubsubMessageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushPubsubMessageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushPubsubMessageResponseValidationError{}

// Validate checks the field values on PubsubMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PubsubMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PubsubMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PubsubMessageMultiError, or
// nil if none found.
func (m *PubsubMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *PubsubMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	// no validation rules for Attributes

	if len(errors) > 0 {
		return PubsubMessageMultiError(errors)
	}

	return nil
}

// PubsubMessageMultiError is an error wrapping multiple validation errors
// returned by PubsubMessage.ValidateAll() if the designated constraints
// aren't met.
type PubsubMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PubsubMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PubsubMessageMultiError) AllErrors() []error { return m }

// PubsubMessageValidationError is the validation error returned by
// PubsubMessage.Validate if the designated constraints aren't met.
type PubsubMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PubsubMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PubsubMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PubsubMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PubsubMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PubsubMessageValidationError) ErrorName() string { return "PubsubMessageValidationError" }

// Error satisfies the builtin error interface
func (e PubsubMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPubsubMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PubsubMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PubsubMessageValidationError{}
