// Code generated by protoc-gen-defaults. DO NOT EDIT.

package pubsubv1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *PushPubsubMessageRequest) Default() {
}

func (x *PushPubsubMessageResponse) Default() {
}

func (x *PubsubMessage) Default() {
}
